services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: finance_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - lab3_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d finance_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  parser:
    build:
      context: .
      dockerfile: parser/Dockerfile
    environment:
      DB_URL: postgresql://postgres:postgres@db:5432/finance_db
    ports:
      - "8001:8001"
    depends_on:
      db:
        condition: service_healthy

  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    environment:
      PARSER_URL: http://parser:8001
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    ports:
      - "8080:8080"
    depends_on:
      - parser
      - redis

  worker:
    build:
      context: .
      dockerfile: worker/Dockerfile
    environment:
      DB_URL: postgresql://postgres:postgres@db:5432/finance_db
      CELERY_BROKER_URL: redis://redis:6379/0
      CELERY_RESULT_BACKEND: redis://redis:6379/1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

volumes:
  lab3_postgres_data:

